version: '3.7'

services:

  web:
    image: node:8.11.3-slim
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app/web
    ports:
      - 3000:3000
    command: npm start

  test:
    image: node:8.11.3-slim
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app/web
    command: npm test

  cmd:
    image: node:8.11.3-slim
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app/web
    command: /bin/bash
